[project]
name = "dharma_analytics"
version = "0.0.1"
authors = [{ name = "poondladharmendra@gmail.com" }]
requires-python = ">=3.10,<3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=15.4,<15.5",
    "ipykernel",
]

[tool.ruff]
line-length = 120